config/routes.rb
PanPlanner::Application.routes.draw do
  resources :users

  resources :events

  root :to => 'events#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :memberships
  has_many :users, :through => :memberships
  
  attr_accessible :at, :description, :title, :user_tokens
  attr_reader :user_tokens
  
  validates_presence_of :title, :description, :at
  
  def user_tokens=(ids)
    self.user_ids = ids.split(',')
  end
  
  class << self
    
    def for_calendar(date)
      if date.is_a? Range
        range = date
      else
        if date.respond_to?(:year) && date.respond_to?(:month)
          date = { year: date.year, month: date.month}
        end
        raise ArgumentError if (date.keys & [:year, :month]).size < 2

        range = DateTime.civil(date[:year], date[:month], 1)..DateTime.civil(date[:year], date[:month], -1)
      end
      where(at: range).group_by { |e| e.at.strftime('%Y%m%d') }
    end
    
    def next_event
      where('at > ?', DateTime.now).first
    end
    
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :memberships
  has_many :events, :through => :memberships
  
  attr_accessible :email, :github_username, :name
  
  validates_presence_of :email, :github_username, :name
  validates_format_of :email, with: /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/ 
  
  class << self
    def tokens(query)
      where("name like ?", "#{query}%")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  inherit_resources
  
  http_basic_authenticate_with name: ENV['HTTP_USER'] || 'admin', password: ENV['HTTP_PASSWORD'] || 'admin', except: [:index, :show]
  
  def index
    date_params = params.symbolize_keys.slice(:year, :month).transform_values(&:to_i)
    @event_date = DateTime.now.change date_params
    @calendar = LaterDude::Calendar.new(@event_date.year, @event_date.month, use_full_day_names: true, first_day_of_week: 1, hide_month_name: true, yield_surrounding_days: true)
    @events = Event.for_calendar(@calendar.first_rendered_date..@calendar.last_rendered_date)
    @next_event = Event.next_event
    index!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  inherit_resources
  
  http_basic_authenticate_with name: ENV['HTTP_USER'] || 'admin', password: ENV['HTTP_PASSWORD'] || 'admin', except: [:index, :show]
  
  def index
    @users = User.order(:name)
    index! do |format|
      format.json { render json: @users.tokens(params[:q]) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    @markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML,
              :autolink => true, :space_after_headers => true)
    @markdown.render(text).html_safe
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_list(users, opt = {})
    separator = opt.delete(:separator) || ' '
    opt.merge!(target: '_blank')
    users.map do |u| 
      opt[:href] = "https://github.com/#{u.github_username}"
      content_tag 'a', u.name, opt 
    end.join(separator.to_s)
  end
end

app/views/events/_form.html.slim
#new_event
  = simple_form_for @event, :html => { :class => "form-horizontal" } do |f|
    = f.input :title
    = f.input :description
    = f.input :at
    = f.input :user_tokens, input_html: { data: { load: @event.users } }
    .form-actions
      = f.button :submit, :class => 'btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), events_path, :class => 'btn'

app/views/events/edit.html.slim
- model_class = @event.class
div class="page-header"
  h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/events/index.html.slim
#calendar
  #event_header
    div.pull-right.next_event
      h3 Next event
      - if @next_event.nil?
        p No event, go ahead and create one
      - else
        p: a href=event_path(@next_event)
          = @next_event.at.to_formatted_s(:long)
          ' :
          = @next_event.title
      a.btn.btn-primary href=new_event_path Add event
    h1.year = @event_date.year
    h2.month = @event_date.strftime('%B')
  = @calendar.to_html do |day|
    - key = day.strftime('%Y%m%d')
    - capture do
      = day.day
      div.event
      - if @events.has_key? key
        - @events[key].each do |event|
          div.event
            a.label.label-info href=event_path(event) = event.title.squish.truncate(20)

app/views/events/new.html.slim
- model_class = @event.class
div class="page-header"
  h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/events/show.html.slim
#event
  div class="page-header"
    h1.clearfix
     span.pull-left = @event.title
     span.label.label-important.pull-left.event_date = @event.at.to_formatted_s(:long)

  p = markdown @event.description
  
  - unless @event.users.empty?
    strong = 'Responsible'
    br
    p == user_list(@event.users)

  .form-actions
    = link_to t('.back', :default => t("helpers.links.back")), events_path, :class => 'btn'
    '
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_event_path(@event), :class => 'btn'
    '
    = link_to t('.destroy', :default => t("helpers.links.destroy")), event_path(@event), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    title Planner
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = favicon_link_tag
  body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          a.btn.btn-navbar data-toggle="collapse" data-target=".nav-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand href=root_path Planner
          .nav-collapse
            ul.nav
              li: a href=events_path Events  
              li: a href=users_path Users  
    #container
      = yield

app/views/users/_form.html.slim
= simple_form_for @user, :html => { :class => "form-horizontal" } do |f|
  = f.input :name
  = f.input :github_username
  = f.input :email
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    '
    = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/edit.html.slim
- model_class = @user.class
div class="page-header"
  h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/users/index.html.slim
- if @users.empty?
  .well No users
- else
  table class="table table-striped"
    thead
      tr
        th Name
        th Github username
        th Email
        th = t '.actions', :default => t("helpers.actions")
    tbody
      - @users.each do |user|
        tr
          td = link_to user.name, user_path(user)
          td == user_list([user])
          td = user.email
          td
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-mini'
            '
            = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.slim
- model_class = @user.class
div class="page-header"
  h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/users/show.html.slim
- model_class = @user.class
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @user.name
p
  strong= model_class.human_attribute_name(:github_username) + ':'
  br
  == user_list([@user])
p
  strong= model_class.human_attribute_name(:email) + ':'
  br
  = @user.email

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn'
  '
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn'
  '
  = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'